<Project>
  <PropertyGroup>
    <Authors>hawkinslabdev</Authors>
    <Company>hawkinslabdev</Company>
    <Copyright>Copyright © 2020-$([System.DateTime]::Now.Year) hawkinslabdev</Copyright>
    <Product>Bark</Product>
    <PackageProjectUrl>https://github.com/hawkinslabdev/bark</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hawkinslabdev/bark</RepositoryUrl>
    <PackageLicenseExpression>EUPL-1.2</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
